# sigmoid

In [ ]:
import tensorflow as tf

In [ ]:
a = tf.constant([4.0, 1.0, 3.0], dtype = tf.float32) # constant: 상수 선언
a, type(a)

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 1., 3.], dtype=float32)>,
 tensorflow.python.framework.ops.EagerTensor)

In [ ]:
b = tf.keras.activations.sigmoid(a)
b

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.98201376, 0.7310586 , 0.95257413], dtype=float32)>

In [ ]:
b.numpy()

array([0.98201376, 0.7310586 , 0.95257413], dtype=float32)

# softmax

In [ ]:
inputs = tf.random.normal(shape=(1, 3))
inputs

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.31372932, 0.23889558, 0.82990205]], dtype=float32)>

In [ ]:
outputs = tf.keras.activations.softmax(inputs)
# outputs

In [ ]:
outputs.numpy()

array([[0.27750796, 0.25749904, 0.46499303]], dtype=float32)

*  분류형의 공식 (hidden layer)

  * 유니크가 3개 이상일때는 activation은 softmax를 쓴다

  * 긍정과 부정처럼 분류가 2개(Binary)인 경우. 이때는 activation을 sigmoid를 쓴다


---


* softmax: node에서 의견을 내서 맨 마지막 output에 들어감. 해당 부분이 아무리 많은 의견이 들어와도 0과 1안으로 수렴시킴. 1에 가까운 결과 값을 찾으면 됨