In [1]:
from sklearn import datasets
import pandas as pd

In [2]:
iris = datasets.load_iris()
df_iris = pd.DataFrame(iris.data)
df_iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       150 non-null    float64
 1   1       150 non-null    float64
 2   2       150 non-null    float64
 3   3       150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [3]:
import sqlite3
connect = sqlite3.connect('./db.sqlite3') # 파일이 생성됐는지 확인
df_iris.to_sql('iris_resource', connect,if_exists= 'append', index= False)

In [4]:
df_load = pd.read_sql_query('select * from iris_resource', connect)
df_load.head(4)

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2

In [5]:
x_data = df_load.to_numpy()
x_data.shape

(150, 4)

In [6]:
import numpy as np

y_data= iris.target
y_data, np.unique(y_data)

# unique한 값 3개 -> output으로 의견을 내야하는 값 (dense 수)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 array([0, 1, 2]))

In [7]:
import tensorflow as tf

In [8]:
model = tf.keras.Sequential()

model.add(tf.keras.Input(shape=(4, ))) # input layer

model.add(tf.keras.layers.Dense(64, activation= 'relu')) # hidden layer
model.add(tf.keras.layers.Dense(34, activation= 'relu')) 

model.add(tf.keras.layers.Dense(3, activation= 'softmax')) # output layer


model.compile(optimizer= 'adam', loss= 'sparse_categorical_crossentropy', metrics= ['acc']) # gadget

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 64)                320       
_________________________________________________________________
dense_1 (Dense)              (None, 34)                2210      
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 105       
Total params: 2,635
Trainable params: 2,635
Non-trainable params: 0
_________________________________________________________________


In [10]:
model.fit(x_data, y_data, epochs= 50, validation_split= 0.3) # 학습

# 전체 양 중에서 0.3만큼 쪼개서 검증

Epoch 1/50
4/4 [==============================] - 1s 76ms/step - loss: 1.0917 - acc: 0.4762 - val_loss: 2.9475 - val_acc: 0.0000e+00
Epoch 2/50
4/4 [==============================] - 0s 13ms/step - loss: 0.9333 - acc: 0.4762 - val_loss: 2.9509 - val_acc: 0.0000e+00
Epoch 3/50
4/4 [==============================] - 0s 11ms/step - loss: 0.8249 - acc: 0.4952 - val_loss: 3.0203 - val_acc: 0.0000e+00
Epoch 4/50
4/4 [==============================] - 0s 17ms/step - loss: 0.7368 - acc: 0.9143 - val_loss: 3.0877 - val_acc: 0.0000e+00
Epoch 5/50
4/4 [==============================] - 0s 11ms/step - loss: 0.6641 - acc: 0.9524 - val_loss: 3.1529 - val_acc: 0.0000e+00
Epoch 6/50
4/4 [==============================] - 0s 12ms/step - loss: 0.6039 - acc: 0.9524 - val_loss: 3.1797 - val_acc: 0.0000e+00
Epoch 7/50
4/4 [==============================] - 0s 12ms/step - loss: 0.5505 - acc: 0.9524 - val_loss: 3.1270 - val_acc: 0.0000e+00
Epoch 8/50
4/4 [==============================] - 0s 10ms/step - loss

# Evaluation

In [11]:
model.evaluate(x_data, y_data)

# 2개(loss, accuracy)의 편차

5/5 [==============================] - 0s 3ms/step - loss: 0.5324 - acc: 0.6667


[0.5323885083198547, 0.6666666865348816]

# Service

In [12]:
x_data[25], y_data[25]

(array([5. , 3. , 1.6, 0.2]), 0)

In [13]:
pred = model.predict([[5. , 3. , 1.6, 0.2]])
pred

# 25번째 데이터를 보니, 1번째 분류일 가능성은 0.3302766, 2번째 분류 0.33684278 ~~

array([[0.97954273, 0.01821433, 0.00224291]], dtype=float32)

In [14]:
import numpy as np

np.argmax(pred)

0