In [4]:
from sklearn import datasets
import pandas as pd

In [5]:
iris = datasets.load_iris()
df_iris = pd.DataFrame(iris.data)
df_iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       150 non-null    float64
 1   1       150 non-null    float64
 2   2       150 non-null    float64
 3   3       150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [6]:
import sqlite3
connect = sqlite3.connect('./db.sqlite3') # 파일이 생성됐는지 확인
df_iris.to_sql('iris_resource', connect,if_exists= 'append', index= False)

In [7]:
df_load = pd.read_sql_query('select * from iris_resource', connect)
df_load.head(4)

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2

In [8]:
x_data = df_load.to_numpy()
x_data.shape

(150, 4)

In [10]:
import numpy as np

y_data= iris.target
y_data, np.unique(y_data)

# unique한 값 3개 -> output으로 의견을 내야하는 값 (dense 수)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 array([0, 1, 2]))

In [11]:
import tensorflow as tf

In [16]:
model = tf.keras.Sequential()

model.add(tf.keras.Input(shape=(4, ))) # input layer

model.add(tf.keras.layers.Dense(64, activation= 'relu')) # hidden layer
model.add(tf.keras.layers.Dense(34, activation= 'relu')) 

model.add(tf.keras.layers.Dense(3, activation= 'softmax')) # output layer


model.compile(optimizer= 'adam', loss= 'mse', metrics= ['acc']) # gadget

In [17]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 64)                320       
_________________________________________________________________
dense_4 (Dense)              (None, 34)                2210      
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 105       
Total params: 2,635
Trainable params: 2,635
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.fit(x_data, y_data, epochs= 50, validation_split= 0.3) # 학습

# 전체 양 중에서 0.3만큼 쪼개서 검증

Epoch 1/50
4/4 [==============================] - 1s 48ms/step - loss: 0.4094 - acc: 0.4667 - val_loss: 2.7840 - val_acc: 0.0000e+00
Epoch 2/50
4/4 [==============================] - 0s 7ms/step - loss: 0.3992 - acc: 0.4762 - val_loss: 2.7791 - val_acc: 0.0000e+00
Epoch 3/50
4/4 [==============================] - 0s 9ms/step - loss: 0.3978 - acc: 0.3143 - val_loss: 2.7821 - val_acc: 0.0000e+00
Epoch 4/50
4/4 [==============================] - 0s 8ms/step - loss: 0.3988 - acc: 0.2952 - val_loss: 2.7812 - val_acc: 0.3333
Epoch 5/50
4/4 [==============================] - 0s 8ms/step - loss: 0.3979 - acc: 0.0476 - val_loss: 2.7787 - val_acc: 0.8444
Epoch 6/50
4/4 [==============================] - 0s 8ms/step - loss: 0.3969 - acc: 0.1905 - val_loss: 2.7779 - val_acc: 0.0667
Epoch 7/50
4/4 [==============================] - 0s 8ms/step - loss: 0.3972 - acc: 0.4667 - val_loss: 2.7782 - val_acc: 0.1111
Epoch 8/50
4/4 [==============================] - 0s 7ms/step - loss: 0.3972 - acc: 0.5048 

# Evaluation

In [19]:
model.evaluate(x_data, y_data)

# 2개(loss, accuracy)의 편차

5/5 [==============================] - 0s 2ms/step - loss: 1.1111 - acc: 0.3467


[1.1111235618591309, 0.3466666638851166]

# Service

In [20]:
x_data[25], y_data[25]

(array([5. , 3. , 1.6, 0.2]), 0)

In [23]:
pred = model.predict([[5. , 3. , 1.6, 0.2]])
pred

# 25번째 데이터를 보니, 1번째 분류일 가능성은 0.3302766, 2번째 분류 0.33684278 ~~

array([[0.3302766 , 0.33684278, 0.33288065]], dtype=float32)

In [24]:
import numpy as np

np.argmax(pred)

1