In [1]:
from sklearn import datasets

wine = datasets.load_wine()
wine.keys()

# wine데이터의 키값 출력: 'data' -> x 데이터, 'target' -> y 데이터

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [2]:
x_data = wine['data']
x_data.shape

(178, 13)

In [3]:
y_data = wine['target']
y_data.shape

(178,)

In [4]:
import pandas as pd

df_wine = pd.DataFrame(wine.data)
df_wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       178 non-null    float64
 1   1       178 non-null    float64
 2   2       178 non-null    float64
 3   3       178 non-null    float64
 4   4       178 non-null    float64
 5   5       178 non-null    float64
 6   6       178 non-null    float64
 7   7       178 non-null    float64
 8   8       178 non-null    float64
 9   9       178 non-null    float64
 10  10      178 non-null    float64
 11  11      178 non-null    float64
 12  12      178 non-null    float64
dtypes: float64(13)
memory usage: 18.2 KB


In [5]:
import sqlite3

connect = sqlite3.connect('./db.sqlite3')
df_wine.to_sql('wine_resource', connect,if_exists= 'append', index= False)

In [6]:
df_load = pd.read_sql_query('select * from wine_resource', connect)
df_load.head(4)

0     1     2     3      4     5  ...     7     8     9    10    11      12
0  14.23  1.71  2.43  15.6  127.0  2.80  ...  0.28  2.29  5.64  1.04  3.92  1065.0
1  13.20  1.78  2.14  11.2  100.0  2.65  ...  0.26  1.28  4.38  1.05  3.40  1050.0
2  13.16  2.36  2.67  18.6  101.0  2.80  ...  0.30  2.81  5.68  1.03  3.17  1185.0
3  14.37  1.95  2.50  16.8  113.0  3.85  ...  0.24  2.18  7.80  0.86  3.45  1480.0

[4 rows x 13 columns]

In [7]:
x_data = df_load.to_numpy()
x_data.shape

(178, 13)

In [8]:
import numpy as np

y_data= wine.target
y_data, np.unique(y_data)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2]), array([0, 1, 2]))

In [9]:
import tensorflow as tf

model = tf.keras.Sequential()

model.add(tf.keras.Input(shape=(13, ))) # input layer

model.add(tf.keras.layers.Dense(64, activation= 'relu')) # hidden layer
model.add(tf.keras.layers.Dense(34, activation= 'relu')) 

model.add(tf.keras.layers.Dense(13, activation= 'softmax')) # output layer


model.compile(optimizer= 'adam', loss= 'sparse_categorical_crossentropy', metrics= ['acc']) # gadget

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 64)                896       
_________________________________________________________________
dense_1 (Dense)              (None, 34)                2210      
_________________________________________________________________
dense_2 (Dense)              (None, 13)                455       
Total params: 3,561
Trainable params: 3,561
Non-trainable params: 0
_________________________________________________________________


# Training

In [11]:
model.fit(x_data, y_data, epochs= 50, validation_split= 0.3)

Epoch 1/50
4/4 [==============================] - 1s 61ms/step - loss: 187.8489 - acc: 0.0000e+00 - val_loss: 79.6541 - val_acc: 0.0000e+00
Epoch 2/50
4/4 [==============================] - 0s 8ms/step - loss: 103.6071 - acc: 0.0000e+00 - val_loss: 52.8413 - val_acc: 0.0000e+00
Epoch 3/50
4/4 [==============================] - 0s 8ms/step - loss: 38.4694 - acc: 0.0323 - val_loss: 47.9590 - val_acc: 0.0000e+00
Epoch 4/50
4/4 [==============================] - 0s 8ms/step - loss: 11.2578 - acc: 0.4435 - val_loss: 59.2932 - val_acc: 0.0000e+00
Epoch 5/50
4/4 [==============================] - 0s 8ms/step - loss: 11.2262 - acc: 0.1371 - val_loss: 67.7191 - val_acc: 0.0000e+00
Epoch 6/50
4/4 [==============================] - 0s 9ms/step - loss: 10.4958 - acc: 0.2581 - val_loss: 81.0860 - val_acc: 0.0000e+00
Epoch 7/50
4/4 [==============================] - 0s 8ms/step - loss: 9.4065 - acc: 0.3871 - val_loss: 80.2390 - val_acc: 0.0000e+00
Epoch 8/50
4/4 [==============================] - 0s

# Evaluation

In [12]:
model.evaluate(x_data, y_data)

6/6 [==============================] - 0s 3ms/step - loss: 26.0794 - acc: 0.6348


[26.079370498657227, 0.6348314881324768]

# Service

In [13]:
x_data[25], y_data[25]

(array([1.305e+01, 2.050e+00, 3.220e+00, 2.500e+01, 1.240e+02, 2.630e+00,
        2.680e+00, 4.700e-01, 1.920e+00, 3.580e+00, 1.130e+00, 3.200e+00,
        8.300e+02]), 0)

In [14]:
pred = model.predict([[1.305e+01, 2.050e+00, 3.220e+00, 2.500e+01, 1.240e+02, 2.630e+00,
        2.680e+00, 4.700e-01, 1.920e+00, 3.580e+00, 1.130e+00, 3.200e+00,
        8.300e+02]])
pred

array([[5.725734e-01, 4.274266e-01, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        1.517721e-35]], dtype=float32)

In [15]:
import numpy as np

np.argmax(pred)

0